version: '3'

services:
  game-server:
    build:
      context: game-server
      args:
        - JAVA_VERSION=arm32v7/eclipse-temurin
        - SERVER_DOWNLOAD_URL=https://necessegame.com/wp-content/uploads/2023/01/necesse-server-linux64-0-21-28-10380663.zip
    restart: unless-stopped
    volumes:
      - /mnt/usb2/conf/Docker/necesse/necesse-dedicated-server-docker-main/save-data:/root/.config/Necesse
    # Unable to figure out how to change the game server to listen on 0.0.0.0,
    # so using this until I can figure that out (probably easiest to add a proxy?)
    network_mode: host
    # ports:
    #   - "14159:14159"
